### ISSUE TITLE
使用jsonrpc时，有时候提示解析错误

### ISSUE THREAD

**Issue by GYbin** [yeqown/rpc#5]
在使用jsonrpc时，如果有一次json的格式错误，下一次如果使用正确的json格式，还是会返回上一次的错误信息。
调试错误的时候发现是 json 下Decoder  中有一个err ， 会记录错误信息。 解析时候会先判断这个err 是不是空，

**Comment by yeqown** [comment]
好的，我看下。另外我声明下，这个库不要用于生产环境。。。

**Comment by yeqown** [comment]
@GYbin 已经修复：每次都使用全新的 decoder 且只使用一次 `Decode`；这里也可以直接使用 json.Unmarshal（dec.DisallowUnknownFields 是默认开启的 ）
